# (1) Слой сборки: ставим git и устанавливаем goose
FROM golang:1.22-alpine AS build

RUN apk add --no-cache git
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

# (2) Финальный образ на базе Alpine
FROM alpine:3.17
RUN apk add --no-cache ca-certificates

# Копируем бинарник goose из слоя build
COPY --from=build /go/bin/goose /usr/local/bin/goose

# Делаем рабочую директорию
WORKDIR /migrations

# По умолчанию внутри контейнера будет выполнена команда "goose"
ENTRYPOINT ["goose"]