// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: inventory/inventory.proto

package inventory

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Inventory_GetItemPrice_FullMethodName        = "/user.Inventory/GetItemPrice"
	Inventory_GetAllItems_FullMethodName         = "/user.Inventory/GetAllItems"
	Inventory_GetAllInventoryInfo_FullMethodName = "/user.Inventory/GetAllInventoryInfo"
	Inventory_UpdatePrice_FullMethodName         = "/user.Inventory/UpdatePrice"
	Inventory_UpdateCountOfItem_FullMethodName   = "/user.Inventory/UpdateCountOfItem"
	Inventory_DeleteItem_FullMethodName          = "/user.Inventory/DeleteItem"
	Inventory_CreateItem_FullMethodName          = "/user.Inventory/CreateItem"
	Inventory_GetItemByRarity_FullMethodName     = "/user.Inventory/GetItemByRarity"
	Inventory_GetItemsByPrice_FullMethodName     = "/user.Inventory/GetItemsByPrice"
)

// InventoryClient is the client API for Inventory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryClient interface {
	GetItemPrice(ctx context.Context, in *GetItemPriceRequest, opts ...grpc.CallOption) (*GetItemPriceResponse, error)
	GetAllItems(ctx context.Context, in *GetAllItemsRequest, opts ...grpc.CallOption) (*GetAllItemsResponse, error)
	GetAllInventoryInfo(ctx context.Context, in *GetAllInventoryInfoRequest, opts ...grpc.CallOption) (*GetAllInventoryInfoResponse, error)
	UpdatePrice(ctx context.Context, in *UpdatePriceRequest, opts ...grpc.CallOption) (*UpdatePriceResponse, error)
	UpdateCountOfItem(ctx context.Context, in *UpdateCountOfItemRequest, opts ...grpc.CallOption) (*UpdateCountOfItemResponse, error)
	DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*DeleteItemResponse, error)
	CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*CreateItemResponse, error)
	GetItemByRarity(ctx context.Context, in *GetItemByRarityRequest, opts ...grpc.CallOption) (*GetItemByRarityResponse, error)
	GetItemsByPrice(ctx context.Context, in *GetItemsByPriceRequest, opts ...grpc.CallOption) (*GetItemsByPriceResponse, error)
}

type inventoryClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryClient(cc grpc.ClientConnInterface) InventoryClient {
	return &inventoryClient{cc}
}

func (c *inventoryClient) GetItemPrice(ctx context.Context, in *GetItemPriceRequest, opts ...grpc.CallOption) (*GetItemPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemPriceResponse)
	err := c.cc.Invoke(ctx, Inventory_GetItemPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) GetAllItems(ctx context.Context, in *GetAllItemsRequest, opts ...grpc.CallOption) (*GetAllItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllItemsResponse)
	err := c.cc.Invoke(ctx, Inventory_GetAllItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) GetAllInventoryInfo(ctx context.Context, in *GetAllInventoryInfoRequest, opts ...grpc.CallOption) (*GetAllInventoryInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllInventoryInfoResponse)
	err := c.cc.Invoke(ctx, Inventory_GetAllInventoryInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) UpdatePrice(ctx context.Context, in *UpdatePriceRequest, opts ...grpc.CallOption) (*UpdatePriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePriceResponse)
	err := c.cc.Invoke(ctx, Inventory_UpdatePrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) UpdateCountOfItem(ctx context.Context, in *UpdateCountOfItemRequest, opts ...grpc.CallOption) (*UpdateCountOfItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCountOfItemResponse)
	err := c.cc.Invoke(ctx, Inventory_UpdateCountOfItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*DeleteItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteItemResponse)
	err := c.cc.Invoke(ctx, Inventory_DeleteItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*CreateItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateItemResponse)
	err := c.cc.Invoke(ctx, Inventory_CreateItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) GetItemByRarity(ctx context.Context, in *GetItemByRarityRequest, opts ...grpc.CallOption) (*GetItemByRarityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemByRarityResponse)
	err := c.cc.Invoke(ctx, Inventory_GetItemByRarity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) GetItemsByPrice(ctx context.Context, in *GetItemsByPriceRequest, opts ...grpc.CallOption) (*GetItemsByPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemsByPriceResponse)
	err := c.cc.Invoke(ctx, Inventory_GetItemsByPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServer is the server API for Inventory service.
// All implementations must embed UnimplementedInventoryServer
// for forward compatibility.
type InventoryServer interface {
	GetItemPrice(context.Context, *GetItemPriceRequest) (*GetItemPriceResponse, error)
	GetAllItems(context.Context, *GetAllItemsRequest) (*GetAllItemsResponse, error)
	GetAllInventoryInfo(context.Context, *GetAllInventoryInfoRequest) (*GetAllInventoryInfoResponse, error)
	UpdatePrice(context.Context, *UpdatePriceRequest) (*UpdatePriceResponse, error)
	UpdateCountOfItem(context.Context, *UpdateCountOfItemRequest) (*UpdateCountOfItemResponse, error)
	DeleteItem(context.Context, *DeleteItemRequest) (*DeleteItemResponse, error)
	CreateItem(context.Context, *CreateItemRequest) (*CreateItemResponse, error)
	GetItemByRarity(context.Context, *GetItemByRarityRequest) (*GetItemByRarityResponse, error)
	GetItemsByPrice(context.Context, *GetItemsByPriceRequest) (*GetItemsByPriceResponse, error)
	mustEmbedUnimplementedInventoryServer()
}

// UnimplementedInventoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryServer struct{}

func (UnimplementedInventoryServer) GetItemPrice(context.Context, *GetItemPriceRequest) (*GetItemPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemPrice not implemented")
}
func (UnimplementedInventoryServer) GetAllItems(context.Context, *GetAllItemsRequest) (*GetAllItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllItems not implemented")
}
func (UnimplementedInventoryServer) GetAllInventoryInfo(context.Context, *GetAllInventoryInfoRequest) (*GetAllInventoryInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllInventoryInfo not implemented")
}
func (UnimplementedInventoryServer) UpdatePrice(context.Context, *UpdatePriceRequest) (*UpdatePriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePrice not implemented")
}
func (UnimplementedInventoryServer) UpdateCountOfItem(context.Context, *UpdateCountOfItemRequest) (*UpdateCountOfItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCountOfItem not implemented")
}
func (UnimplementedInventoryServer) DeleteItem(context.Context, *DeleteItemRequest) (*DeleteItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteItem not implemented")
}
func (UnimplementedInventoryServer) CreateItem(context.Context, *CreateItemRequest) (*CreateItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateItem not implemented")
}
func (UnimplementedInventoryServer) GetItemByRarity(context.Context, *GetItemByRarityRequest) (*GetItemByRarityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemByRarity not implemented")
}
func (UnimplementedInventoryServer) GetItemsByPrice(context.Context, *GetItemsByPriceRequest) (*GetItemsByPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemsByPrice not implemented")
}
func (UnimplementedInventoryServer) mustEmbedUnimplementedInventoryServer() {}
func (UnimplementedInventoryServer) testEmbeddedByValue()                   {}

// UnsafeInventoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServer will
// result in compilation errors.
type UnsafeInventoryServer interface {
	mustEmbedUnimplementedInventoryServer()
}

func RegisterInventoryServer(s grpc.ServiceRegistrar, srv InventoryServer) {
	// If the following call pancis, it indicates UnimplementedInventoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Inventory_ServiceDesc, srv)
}

func _Inventory_GetItemPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).GetItemPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_GetItemPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).GetItemPrice(ctx, req.(*GetItemPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_GetAllItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).GetAllItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_GetAllItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).GetAllItems(ctx, req.(*GetAllItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_GetAllInventoryInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllInventoryInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).GetAllInventoryInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_GetAllInventoryInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).GetAllInventoryInfo(ctx, req.(*GetAllInventoryInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_UpdatePrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).UpdatePrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_UpdatePrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).UpdatePrice(ctx, req.(*UpdatePriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_UpdateCountOfItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCountOfItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).UpdateCountOfItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_UpdateCountOfItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).UpdateCountOfItem(ctx, req.(*UpdateCountOfItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_DeleteItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).DeleteItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_DeleteItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).DeleteItem(ctx, req.(*DeleteItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_CreateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).CreateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_CreateItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).CreateItem(ctx, req.(*CreateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_GetItemByRarity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemByRarityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).GetItemByRarity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_GetItemByRarity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).GetItemByRarity(ctx, req.(*GetItemByRarityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_GetItemsByPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemsByPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).GetItemsByPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_GetItemsByPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).GetItemsByPrice(ctx, req.(*GetItemsByPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Inventory_ServiceDesc is the grpc.ServiceDesc for Inventory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Inventory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.Inventory",
	HandlerType: (*InventoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItemPrice",
			Handler:    _Inventory_GetItemPrice_Handler,
		},
		{
			MethodName: "GetAllItems",
			Handler:    _Inventory_GetAllItems_Handler,
		},
		{
			MethodName: "GetAllInventoryInfo",
			Handler:    _Inventory_GetAllInventoryInfo_Handler,
		},
		{
			MethodName: "UpdatePrice",
			Handler:    _Inventory_UpdatePrice_Handler,
		},
		{
			MethodName: "UpdateCountOfItem",
			Handler:    _Inventory_UpdateCountOfItem_Handler,
		},
		{
			MethodName: "DeleteItem",
			Handler:    _Inventory_DeleteItem_Handler,
		},
		{
			MethodName: "CreateItem",
			Handler:    _Inventory_CreateItem_Handler,
		},
		{
			MethodName: "GetItemByRarity",
			Handler:    _Inventory_GetItemByRarity_Handler,
		},
		{
			MethodName: "GetItemsByPrice",
			Handler:    _Inventory_GetItemsByPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory/inventory.proto",
}
