// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: trading/trading.proto

package trading

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Trading_CreateTrade_FullMethodName        = "/trading.Trading/CreateTrade"
	Trading_AcceptTrade_FullMethodName        = "/trading.Trading/AcceptTrade"
	Trading_DeclineTrade_FullMethodName       = "/trading.Trading/DeclineTrade"
	Trading_GetTrade_FullMethodName           = "/trading.Trading/GetTrade"
	Trading_GetAllTrades_FullMethodName       = "/trading.Trading/GetAllTrades"
	Trading_GetHistoryOfTrades_FullMethodName = "/trading.Trading/GetHistoryOfTrades"
	Trading_GetTradesByStatus_FullMethodName  = "/trading.Trading/GetTradesByStatus"
	Trading_DeleteTrade_FullMethodName        = "/trading.Trading/DeleteTrade"
)

// TradingClient is the client API for Trading service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradingClient interface {
	CreateTrade(ctx context.Context, in *CreateTradeRequest, opts ...grpc.CallOption) (*CreateTradeResponse, error)
	AcceptTrade(ctx context.Context, in *AcceptTradeRequest, opts ...grpc.CallOption) (*AcceptTradeResponse, error)
	DeclineTrade(ctx context.Context, in *DeclineTradeRequest, opts ...grpc.CallOption) (*DeclineTradeResponse, error)
	GetTrade(ctx context.Context, in *GetTradeRequest, opts ...grpc.CallOption) (*GetTradeResponse, error)
	GetAllTrades(ctx context.Context, in *GetAllTradesRequest, opts ...grpc.CallOption) (*GetAllTradesResponse, error)
	GetHistoryOfTrades(ctx context.Context, in *GetHistoryOfTradesRequest, opts ...grpc.CallOption) (*GetHistoryOfTradesResponse, error)
	GetTradesByStatus(ctx context.Context, in *GetTradesByStatusRequest, opts ...grpc.CallOption) (*GetTradesByStatusResponse, error)
	DeleteTrade(ctx context.Context, in *DeleteTradeRequest, opts ...grpc.CallOption) (*DeleteTradeResponse, error)
}

type tradingClient struct {
	cc grpc.ClientConnInterface
}

func NewTradingClient(cc grpc.ClientConnInterface) TradingClient {
	return &tradingClient{cc}
}

func (c *tradingClient) CreateTrade(ctx context.Context, in *CreateTradeRequest, opts ...grpc.CallOption) (*CreateTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTradeResponse)
	err := c.cc.Invoke(ctx, Trading_CreateTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingClient) AcceptTrade(ctx context.Context, in *AcceptTradeRequest, opts ...grpc.CallOption) (*AcceptTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptTradeResponse)
	err := c.cc.Invoke(ctx, Trading_AcceptTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingClient) DeclineTrade(ctx context.Context, in *DeclineTradeRequest, opts ...grpc.CallOption) (*DeclineTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeclineTradeResponse)
	err := c.cc.Invoke(ctx, Trading_DeclineTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingClient) GetTrade(ctx context.Context, in *GetTradeRequest, opts ...grpc.CallOption) (*GetTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTradeResponse)
	err := c.cc.Invoke(ctx, Trading_GetTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingClient) GetAllTrades(ctx context.Context, in *GetAllTradesRequest, opts ...grpc.CallOption) (*GetAllTradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllTradesResponse)
	err := c.cc.Invoke(ctx, Trading_GetAllTrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingClient) GetHistoryOfTrades(ctx context.Context, in *GetHistoryOfTradesRequest, opts ...grpc.CallOption) (*GetHistoryOfTradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryOfTradesResponse)
	err := c.cc.Invoke(ctx, Trading_GetHistoryOfTrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingClient) GetTradesByStatus(ctx context.Context, in *GetTradesByStatusRequest, opts ...grpc.CallOption) (*GetTradesByStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTradesByStatusResponse)
	err := c.cc.Invoke(ctx, Trading_GetTradesByStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingClient) DeleteTrade(ctx context.Context, in *DeleteTradeRequest, opts ...grpc.CallOption) (*DeleteTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTradeResponse)
	err := c.cc.Invoke(ctx, Trading_DeleteTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradingServer is the server API for Trading service.
// All implementations must embed UnimplementedTradingServer
// for forward compatibility.
type TradingServer interface {
	CreateTrade(context.Context, *CreateTradeRequest) (*CreateTradeResponse, error)
	AcceptTrade(context.Context, *AcceptTradeRequest) (*AcceptTradeResponse, error)
	DeclineTrade(context.Context, *DeclineTradeRequest) (*DeclineTradeResponse, error)
	GetTrade(context.Context, *GetTradeRequest) (*GetTradeResponse, error)
	GetAllTrades(context.Context, *GetAllTradesRequest) (*GetAllTradesResponse, error)
	GetHistoryOfTrades(context.Context, *GetHistoryOfTradesRequest) (*GetHistoryOfTradesResponse, error)
	GetTradesByStatus(context.Context, *GetTradesByStatusRequest) (*GetTradesByStatusResponse, error)
	DeleteTrade(context.Context, *DeleteTradeRequest) (*DeleteTradeResponse, error)
	mustEmbedUnimplementedTradingServer()
}

// UnimplementedTradingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTradingServer struct{}

func (UnimplementedTradingServer) CreateTrade(context.Context, *CreateTradeRequest) (*CreateTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTrade not implemented")
}
func (UnimplementedTradingServer) AcceptTrade(context.Context, *AcceptTradeRequest) (*AcceptTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptTrade not implemented")
}
func (UnimplementedTradingServer) DeclineTrade(context.Context, *DeclineTradeRequest) (*DeclineTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeclineTrade not implemented")
}
func (UnimplementedTradingServer) GetTrade(context.Context, *GetTradeRequest) (*GetTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrade not implemented")
}
func (UnimplementedTradingServer) GetAllTrades(context.Context, *GetAllTradesRequest) (*GetAllTradesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTrades not implemented")
}
func (UnimplementedTradingServer) GetHistoryOfTrades(context.Context, *GetHistoryOfTradesRequest) (*GetHistoryOfTradesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistoryOfTrades not implemented")
}
func (UnimplementedTradingServer) GetTradesByStatus(context.Context, *GetTradesByStatusRequest) (*GetTradesByStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTradesByStatus not implemented")
}
func (UnimplementedTradingServer) DeleteTrade(context.Context, *DeleteTradeRequest) (*DeleteTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTrade not implemented")
}
func (UnimplementedTradingServer) mustEmbedUnimplementedTradingServer() {}
func (UnimplementedTradingServer) testEmbeddedByValue()                 {}

// UnsafeTradingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradingServer will
// result in compilation errors.
type UnsafeTradingServer interface {
	mustEmbedUnimplementedTradingServer()
}

func RegisterTradingServer(s grpc.ServiceRegistrar, srv TradingServer) {
	// If the following call pancis, it indicates UnimplementedTradingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Trading_ServiceDesc, srv)
}

func _Trading_CreateTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServer).CreateTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trading_CreateTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServer).CreateTrade(ctx, req.(*CreateTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trading_AcceptTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServer).AcceptTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trading_AcceptTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServer).AcceptTrade(ctx, req.(*AcceptTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trading_DeclineTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeclineTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServer).DeclineTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trading_DeclineTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServer).DeclineTrade(ctx, req.(*DeclineTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trading_GetTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServer).GetTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trading_GetTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServer).GetTrade(ctx, req.(*GetTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trading_GetAllTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllTradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServer).GetAllTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trading_GetAllTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServer).GetAllTrades(ctx, req.(*GetAllTradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trading_GetHistoryOfTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryOfTradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServer).GetHistoryOfTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trading_GetHistoryOfTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServer).GetHistoryOfTrades(ctx, req.(*GetHistoryOfTradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trading_GetTradesByStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTradesByStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServer).GetTradesByStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trading_GetTradesByStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServer).GetTradesByStatus(ctx, req.(*GetTradesByStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trading_DeleteTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServer).DeleteTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trading_DeleteTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServer).DeleteTrade(ctx, req.(*DeleteTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Trading_ServiceDesc is the grpc.ServiceDesc for Trading service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Trading_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trading.Trading",
	HandlerType: (*TradingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrade",
			Handler:    _Trading_CreateTrade_Handler,
		},
		{
			MethodName: "AcceptTrade",
			Handler:    _Trading_AcceptTrade_Handler,
		},
		{
			MethodName: "DeclineTrade",
			Handler:    _Trading_DeclineTrade_Handler,
		},
		{
			MethodName: "GetTrade",
			Handler:    _Trading_GetTrade_Handler,
		},
		{
			MethodName: "GetAllTrades",
			Handler:    _Trading_GetAllTrades_Handler,
		},
		{
			MethodName: "GetHistoryOfTrades",
			Handler:    _Trading_GetHistoryOfTrades_Handler,
		},
		{
			MethodName: "GetTradesByStatus",
			Handler:    _Trading_GetTradesByStatus_Handler,
		},
		{
			MethodName: "DeleteTrade",
			Handler:    _Trading_DeleteTrade_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trading/trading.proto",
}
